# Generated by Django 4.1.3 on 2022-11-17 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candycanes_store_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
