# Generated by Django 4.1.2 on 2022-11-18 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candycanes_store_app', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='checkout_item',
            field=models.BooleanField(default=False),
        ),
    ]
